//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZakCmsSetup.Properties
{


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZakCmsSetup.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Completed!.
		/// </summary>
		internal static string completed_message
		{
			get
			{
				return ResourceManager.GetString("completed_message", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Default-ContactUs.
		/// </summary>
		internal static string defau_contactus
		{
			get
			{
				return ResourceManager.GetString("defau_contactus", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Default-HomePage.
		/// </summary>
		internal static string defau_home
		{
			get
			{
				return ResourceManager.GetString("defau_home", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Default-Projects.
		/// </summary>
		internal static string defau_projects
		{
			get
			{
				return ResourceManager.GetString("defau_projects", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Default-Who.
		/// </summary>
		internal static string defau_who
		{
			get
			{
				return ResourceManager.GetString("defau_who", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Contact Us.
		/// </summary>
		internal static string en_us_contactus
		{
			get
			{
				return ResourceManager.GetString("en_us_contactus", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Home Page.
		/// </summary>
		internal static string en_us_home
		{
			get
			{
				return ResourceManager.GetString("en_us_home", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Our Projects.
		/// </summary>
		internal static string en_us_projects
		{
			get
			{
				return ResourceManager.GetString("en_us_projects", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Restricted Page.
		/// </summary>
		internal static string en_us_restricted
		{
			get
			{
				return ResourceManager.GetString("en_us_restricted", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Who we are.
		/// </summary>
		internal static string en_us_who
		{
			get
			{
				return ResourceManager.GetString("en_us_who", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Contactez-nous.
		/// </summary>
		internal static string fr_fr_contactus
		{
			get
			{
				return ResourceManager.GetString("fr_fr_contactus", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Page principale.
		/// </summary>
		internal static string fr_fr_home
		{
			get
			{
				return ResourceManager.GetString("fr_fr_home", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Nos Projects.
		/// </summary>
		internal static string fr_fr_projects
		{
			get
			{
				return ResourceManager.GetString("fr_fr_projects", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Page privee.
		/// </summary>
		internal static string fr_fr_restricted
		{
			get
			{
				return ResourceManager.GetString("fr_fr_restricted", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Qui nous sommes.
		/// </summary>
		internal static string fr_fr_who
		{
			get
			{
				return ResourceManager.GetString("fr_fr_who", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Conttati.
		/// </summary>
		internal static string it_it_contactus
		{
			get
			{
				return ResourceManager.GetString("it_it_contactus", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Pagina principale.
		/// </summary>
		internal static string it_it_home
		{
			get
			{
				return ResourceManager.GetString("it_it_home", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to I Nostri Progetti.
		/// </summary>
		internal static string it_it_projects
		{
			get
			{
				return ResourceManager.GetString("it_it_projects", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Pagina Privata.
		/// </summary>
		internal static string it_it_restricted
		{
			get
			{
				return ResourceManager.GetString("it_it_restricted", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Chi siamo.
		/// </summary>
		internal static string it_it_who
		{
			get
			{
				return ResourceManager.GetString("it_it_who", resourceCulture);
			}
		}
	}
}
